<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('jobs')->delete();

        \DB::table('jobs')->insert(array (
            0 =>
            array (
                'id' => 1,
                'job_code' => 'dinhtu',
                'job_name' => 'dinhtu',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => '1
2
3',
                'job_period' => '44',
                'type_of_job' => 1,
                'office_towns' => '5
6
7',
                'genres' => '[]',
                'areas' => '[{"id": "2"}, {"id": "6"}, {"id": "2"}, {"id": "6"}]',
                'skills' => '[{"id": "2"}, {"id": "6"}, {"id": "10"}, {"id": "14"}, {"id": "18"}, {"id": "22"}, {"id": "26"}, {"id": "30"}, {"id": "34"}, {"id": "38"}, {"id": "42"}, {"id": "46"}, {"id": "50"}]',
                'desired_costs' => '[{"id": "2"}, {"id": "6"}]',
                'features' => '[{"id": "2"}, {"id": "6"}, {"id": "10"}, {"id": "14"}, {"id": "18"}]',
                'job_publish_start_date' => '2022-06-02 15:14:00',
                'job_publish_end_date' => '2022-06-04 15:14:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-03 17:14:59',
                'updated_at' => '2022-06-03 17:19:46',
                'deleted_at' => '2022-06-03 17:19:46',
            ),
            1 =>
            array (
                'id' => 2,
                'job_code' => 'dinhtu',
                'job_name' => 'dinhtu',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円〜',
                'job_match_skill' => '1
2
3',
                'job_period' => '44',
                'type_of_job' => 1,
                'office_towns' => '5
6
7',
                'genres' => '[{"id": "2"}, {"id": "6"}]',
                'areas' => '[{"id": "2"}, {"id": "6"}]',
                'skills' => '[{"id": "1"}, {"id": "2"}, {"id": "5"}, {"id": "6"}, {"id": "9"}, {"id": "10"}, {"id": "13"}, {"id": "14"}, {"id": "17"}, {"id": "18"}, {"id": "21"}, {"id": "22"}, {"id": "25"}, {"id": "26"}, {"id": "30"}, {"id": "34"}, {"id": "38"}, {"id": "42"}, {"id": "46"}, {"id": "50"}]',
                'desired_costs' => '[{"id": "2"}, {"id": "6"}]',
                'features' => '[{"id": "2"}, {"id": "6"}, {"id": "10"}, {"id": "14"}, {"id": "18"}]',
                'job_publish_start_date' => '2022-07-01 15:20:00',
                'job_publish_end_date' => '2022-07-03 15:20:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-03 17:20:50',
                'updated_at' => '2022-06-04 12:15:26',
                'deleted_at' => '2022-06-04 12:15:26',
            ),
            2 =>
            array (
                'id' => 3,
                'job_code' => 'Job001',
                'job_name' => 'Webアプリ開発',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "1"}]',
                'areas' => '[{"id": "2"}]',
                'skills' => '[{"id": "1"}, {"id": "5"}]',
                'desired_costs' => '[{"id": "6"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:21:00',
                'job_publish_end_date' => '2022-08-31 10:21:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:21:26',
                'updated_at' => '2022-06-04 12:54:56',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'job_code' => 'Job002',
                'job_name' => '業務アプリ業務',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "2"}]',
                'areas' => '[{"id": "5"}]',
                'skills' => '[{"id": "14"}, {"id": "17"}]',
                'desired_costs' => '[{"id": "2"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:21:00',
                'job_publish_end_date' => '2022-08-23 10:21:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:21:58',
                'updated_at' => '2022-06-04 12:54:48',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'job_code' => 'Job003',
                'job_name' => 'インフラ/運用/基盤系',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "3"}]',
                'areas' => '[{"id": "6"}]',
                'skills' => '[{"id": "3"}, {"id": "7"}]',
                'desired_costs' => '[{"id": "3"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:22:00',
                'job_publish_end_date' => '2022-07-03 10:22:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:22:28',
                'updated_at' => '2022-06-04 12:54:18',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'job_code' => 'Job004',
                'job_name' => 'PM/PMO/コンサルなど',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "4"}]',
                'areas' => '[{"id": "5"}]',
                'skills' => '[{"id": "26"}, {"id": "38"}]',
                'desired_costs' => '[{"id": "1"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:22:00',
                'job_publish_end_date' => '2022-07-30 10:22:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:22:52',
                'updated_at' => '2022-06-04 12:54:00',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'job_code' => 'Job005',
                'job_name' => 'VB/VBA',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "5"}]',
                'areas' => '[{"id": "4"}]',
                'skills' => '[{"id": "42"}, {"id": "43"}, {"id": "44"}]',
                'desired_costs' => '[{"id": "5"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:23:00',
                'job_publish_end_date' => '2022-07-31 10:23:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:23:28',
                'updated_at' => '2022-06-04 12:53:50',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'job_code' => 'Job006',
                'job_name' => '汎用機系',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "6"}]',
                'areas' => '[{"id": "3"}]',
                'skills' => '[{"id": "13"}, {"id": "18"}]',
                'desired_costs' => '[{"id": "6"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-01 10:23:00',
                'job_publish_end_date' => '2022-07-31 10:23:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:23:56',
                'updated_at' => '2022-06-04 12:53:40',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'job_code' => 'Job007',
                'job_name' => '組込系/制御系',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "7"}]',
                'areas' => '[{"id": "2"}]',
                'skills' => '[{"id": "6"}, {"id": "10"}]',
                'desired_costs' => '[{"id": "2"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-02 10:24:00',
                'job_publish_end_date' => '2022-06-28 10:24:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:24:33',
                'updated_at' => '2022-06-04 12:53:32',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'job_code' => 'Job008',
                'job_name' => 'Webアプリ開発/VB/VBA',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "1"}, {"id": "5"}]',
                'areas' => '[{"id": "1"}]',
                'skills' => '[{"id": "37"}, {"id": "41"}, {"id": "45"}]',
                'desired_costs' => '[{"id": "6"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-03 10:25:00',
                'job_publish_end_date' => '2022-07-31 10:25:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:25:16',
                'updated_at' => '2022-06-04 12:53:21',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'job_code' => 'Job009',
                'job_name' => 'インフラ/運用/基盤系/汎用機系',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "3"}, {"id": "6"}]',
                'areas' => '[{"id": "5"}]',
                'skills' => '[{"id": "18"}, {"id": "22"}]',
                'desired_costs' => '[{"id": "6"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-03 10:25:00',
                'job_publish_end_date' => '2022-07-02 10:25:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:25:50',
                'updated_at' => '2022-06-04 12:53:13',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'job_code' => 'Job0010',
                'job_name' => 'VB/VBA/C#',
                'job_cost_start' => '90万円〜',
                'job_cost_end' => '90万円',
                'job_match_skill' => NULL,
                'job_period' => NULL,
                'type_of_job' => 0,
                'office_towns' => NULL,
                'genres' => '[{"id": "2"}, {"id": "5"}]',
                'areas' => '[{"id": "2"}]',
                'skills' => '[{"id": "14"}, {"id": "18"}]',
                'desired_costs' => '[{"id": "5"}]',
                'features' => '[]',
                'job_publish_start_date' => '2022-06-02 10:26:00',
                'job_publish_end_date' => '2022-07-31 10:26:00',
                'job_publish_status' => 1,
                'created_at' => '2022-06-04 12:26:23',
                'updated_at' => '2022-06-04 12:53:02',
                'deleted_at' => NULL,
            ),
        ));


    }
}
